### ISSUE TITLE
[Feature] Download a video

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#102]
## Problem
For any resource that contains a video, the download button does not download the video but redirects it to creative common's website

## Description
The download button is misleading for users. Instead of redirecting the video to the new url, the video can be downloaded. 
Or the **Download** button could be changed to a **View** button for viewing it on creative common's website.

<img width="1107" alt="Screenshot 2023-03-22 at 4 53 18 PM" src="https://user-images.githubusercontent.com/77684943/226890642-d0558482-6088-44e3-a1e9-7454461f0dbd.png">

## Alternatives
An alternative could be providing two buttons, one for downloading the video and one for redirecting to creative common's website.
Like this:
<img width="971" alt="Screenshot 2023-03-22 at 5 05 16 PM" src="https://user-images.githubusercontent.com/77684943/226892381-279bd0f2-bb13-46b1-84bf-5dcf3653e471.png">

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
It might be better to just remove the download button if its not functioning as expected on these items. I think removing it, or changing to view where appropriate is a good solutions.

@Xaid-vfx You've got some other contributions I think we should open this up to anyone else that wants to tackle it.

**Comment by shuence** [comment]
Hey I want to work on this, Can you assign me ?

**Comment by Xaid-vfx** [comment]
Sure @possumbilities.
Anyone who wishes to take up on this issue is more than welcome. Please let me if you need any sort of help while fixing the issue, I'd be happy to help.

**Comment by pushkar707** [comment]
Hey @Xaid-vfx, I want to work on this issue, I wish to work on this project through GSOC, I want to make contribution to this project before I can write my proposal for creative commons on GSOC

**Comment by MeowthyVoyager** [comment]
I am working on this issue.

**Comment by shuence** [comment]
> It might be better to just remove the download button if its not functioning as expected on these items. I think removing it, or changing to view where appropriate is a good solutions.
> 
> @Xaid-vfx You've got some other contributions I think we should open this up to anyone else that wants to tackle it.

Another approach could be to add downlodable video link in downloadUrl Parameter.

**Comment by nandu-99** [comment]
can you please assign this issue to me?, I want to work on this issue!

**Comment by possumbilities** [comment]
@Murdock9803 I've assigned you.

**Comment by Murdock9803** [comment]
@possumbilities @annatuma  
I have solved the issue, also added some extra width to the button. Please have a look
