### ISSUE TITLE
[Feature] Adding Footer

### ISSUE THREAD

**Issue by shuence** [creativecommons/cc-resource-archive#104]
## Problem

There is No footer Section

## Description

Adding footer for showing contact information about Creative Commons.

## Implementation

![image](https://user-images.githubusercontent.com/65482186/226956610-c19e440b-63f0-4155-a087-581a6c6c00c7.png)

- [x] I would be interested in implementing this feature.

**Comment by devcode8** [comment]
I want to work on this issue please assign me this issue.

**Comment by justaskulkarni** [comment]
This issue is same as #65 and #34

**Comment by possumbilities** [comment]
closing as duplicate
