### ISSUE TITLE
[Feature] Removing unnecessary JavaScript functions

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#105]
## Problem
There exists two functions that I came across that does nothing in our website

## Description
The functions `UpdateQueryString()` and `RemoveQueryString()` present in **"listing.html"** are non-functional. Upon investigation, I have found that these functions are not being called anywhere in the code. After removing them, I tested the website's functionality, and it worked perfectly fine. The intended purpose of these functions was to update the URL as filters are applied and removed, but this functionality is already present in "**all.html"**.

<img width="635" alt="Screenshot 2023-03-23 at 4 25 43 PM" src="https://user-images.githubusercontent.com/77684943/227182483-9c05f7f8-526f-4cae-aa53-711039226542.png">

It would be a good approach to remove these functions unless necessary as they are creating confusion in the codebase.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
@possumbilities could you provide a feedback regarding this?

**Comment by digi-booster** [comment]
Hi @Xaid-vfx, It's ready to work now, are you still interested in implementing it?

**Comment by Xaid-vfx** [comment]
@digi-booster yes, I am taking up this issue.
