### ISSUE TITLE
[Feature] <Adding responsive nav bar >

### ISSUE THREAD

**Issue by devcode8** [creativecommons/cc-resource-archive#107]
## Problem
It require a good UI Nav bar as logo floating in left side in all screen look not good.

## Description
Site must contain a good nav bar on header
<img width="1468" alt="Screenshot 2023-03-23 at 11 44 37 PM" src="https://user-images.githubusercontent.com/111856910/227308214-4e667dae-2858-4bad-a18d-d9ff561a3446.png">

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by arjunsaxena122** [comment]
_can you assign this issue to me_

**Comment by justaskulkarni** [comment]
This issue is the same as #48 so the discussion can be moved over there rather than having two separate issues for the same topic.

**Comment by op-amateur** [comment]
Hello, I would like to work on this issue.

**Comment by possumbilities** [comment]
Closing as duplicate
