### ISSUE TITLE
[Feature] <Require a good UI interface for list section>

### ISSUE THREAD

**Issue by devcode8** [creativecommons/cc-resource-archive#108]
## Problem
The data list is not in good ui and not responsive

## Description
Site require a good redesign section of this with good implementation of UI
<img width="1441" alt="Screenshot 2023-03-23 at 11 48 20 PM" src="https://user-images.githubusercontent.com/111856910/227309880-8c2b2d1b-3c0a-46e9-be38-c8d2815a6672.png">

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by justaskulkarni** [comment]
This issue is same as #23, so the discussion can be moved over there.

**Comment by possumbilities** [comment]
I agree with @justaskulkarni Closing as duplicate.
