### ISSUE TITLE
Unnecessary <a> tags in resource page

### ISSUE THREAD

**Issue by C-NikhilKarthik** [creativecommons/cc-resource-archive#111]
## Description
Unnecessary <a> tags are used in all the resource pages.

## Reproduction
1. open docs folder
2. then navigate to _site folder
3. all the index.html files in each folder contains this error ( specifically while rendering the title for the page )
4. See error.
5. This is also seen in the resource.html in the _layout file.

## Expectation
remove this redundant a tag as it not only confuses the reader but disrupts the intended working of the website

## Screenshots
![image](https://user-images.githubusercontent.com/100520932/227621108-a26cc37f-9a0d-4dcd-ab43-bf62486ace24.png)
![Screenshot from 2023-03-25 00-51-30](https://user-images.githubusercontent.com/100520932/227621165-0d95c52c-b842-4ea4-be98-24af9b2b99c2.png)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by C-NikhilKarthik** [comment]
@possumbilities can i start working on this issue if you could approve this issue?

**Comment by Lakshay-Pruthi** [comment]
@C-NikhilKarthik  **_site** is a build folder that gets created when you run '**docker compose up**' so you only need to update the resource.html file. Also, I can see the h2 tag is closed with h3 tag so correct that as well after the PR gets approved.

**Comment by C-NikhilKarthik** [comment]
@possumbilities i have raised a [PR](https://github.com/creativecommons/cc-resource-archive/pull/152) , in which i have resolved all the above mentioned fixes. Hope you review the same provide the necessary feedbacks.
