### ISSUE TITLE
[Bug] Site not readable and responsive on mobile devices

### ISSUE THREAD

**Issue by asrvd** [creativecommons/cc-resource-archive#114]
## Description
The current site is readable nicely on large devices but the text is not readable because of very small size on mobile devices (unless zoomed enough), these are responsive issues which can be solved easily by using some CSS. This also affects the accessibility of the site.

## Reproduction
1. Visit https://resources.creativecommons.org on a mobile device.

## Expectation
The site is expected to adjust the positioning and sizing of elements according to screen size for better accessibility.
The issue arises because of the resource cards taking most of the space and font sizes not being adjusted according to screen size. The expected solution would be to use CSS grids for organizing the resource cards and adding some media queries to the CSS file.

## Screenshots
![image](https://user-images.githubusercontent.com/68690233/227700875-2291c262-99ef-4597-8237-2dce313fd147.png)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by asrvd** [comment]
@possumbilities would like to have your thoughts on this and #113 , thank you 😸

**Comment by possumbilities** [comment]
this is a duplicate, please move conversations to the mentioned Issues.
