### ISSUE TITLE
[Feature] Remove unnecessary spaces and format code

### ISSUE THREAD

**Issue by Naman13Kumawat** [creativecommons/cc-resource-archive#115]
## Problem
This is a follow up to the issue #101. 

## Description
All the html files under the "__site_" folder have unnecessary spaces and requires formatting which will improve the readability of the code.
For instance, file present at "_docs\_site\all\index.html_" have more than 2700 lines, but after removing spaces and with proper formatting it reduces to 675 lines of code.

-> index.html before formatting:
![image](https://user-images.githubusercontent.com/85545016/227704958-803cbd4a-020b-49a4-9814-474333f79667.png)

-> index.html after formatting:
![image](https://user-images.githubusercontent.com/85545016/227704997-df18955a-599c-42df-aca8-76f81adbf6d3.png)

## Alternatives
To resolve this issue, we can use any HTML formatting extension. Here I've used [Prettier](https://prettier.io/).

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by arjunsaxena122** [comment]
can you assign this issue to me

**Comment by Naman13Kumawat** [comment]
@arjunsaxena122 Glad to hear that you want to contribute, but since the issue is still under status: awaiting triage, it can't be assigned. I am already interested in working on it as soon as it is open to work and also, it can only be assigned by a mentor.

**Comment by possumbilities** [comment]
@Naman13Kumawat I think it might be better to add this information to #101 so the work is happening on the same Issue since they're so related.

**Comment by Naman13Kumawat** [comment]
@possumbilities Okay I'll add this information to #101 as a comment.
