### ISSUE TITLE
[Bug] Submit a resource button disappears when clicking 'See all' button"

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/cc-resource-archive#118]
## Description
When visiting the resource page, the user is presented with a list of resources and a button to "submit a resource". However, when the user clicks on the "see all" button to view all the resources, the "submit a resource" button disappears. This is a bug that needs to be fixed.

## Reproduction

1. Go to the resource page
2. Observe the "submit a resource" button
3. Click on the "see all" button to view all the resources
4. Observe that the "submit a resource" button disappears
5. See error.

## Expectation
The "submit a resource" button should remain visible even after clicking on the "see all" button.

## Screenshots
Before clicking see all
![image](https://user-images.githubusercontent.com/91469717/227761718-f5ef9f85-217a-4efb-838f-df19ab1873e4.png)

After clicking see all
![image](https://user-images.githubusercontent.com/91469717/227761743-86c4c7c4-3ed2-4f30-ba18-d3d4c478ebc8.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Xaid-vfx** [comment]
Hey @Lakshay-Pruthi ,
Great findings, but I think this issue is already mentioned here #85. You could carry the conversation there.

**Comment by Lakshay-Pruthi** [comment]
@Xaid-vfx Oh!! Thanks for pointing out.
