### ISSUE TITLE
[Feature] Adding a trailing icon on filter text (topic name) and removing existing bracket and text 

### ISSUE THREAD

**Issue by sj-jain** [creativecommons/cc-resource-archive#119]
## Problem
Currently used  bracket and text [X] as a trailing icon for removing filter choice is confusing seems like part of the text itself with no functionality .

## Description
Adding a trailing icon according to vocabulary design language that improves the functionality and user experience for removing a tag or filter . This will also help upcoming fellow contributors to understand the functionality of the filters.

##Screenshots
![image 7](https://user-images.githubusercontent.com/81862008/227782067-3b30b39e-d0af-4195-ab2a-0d20fcf8678f.png)
![image 6](https://user-images.githubusercontent.com/81862008/227782078-cb98deba-e0bc-49e4-a705-03214d022419.png)
![image 8 (3)](https://user-images.githubusercontent.com/81862008/227782085-b896ae47-5954-4023-93ed-15532c3c6dc8.png)

## Implementation
 Replace  [x]  to trailing cross icon svg from vocabulary docs

@possumbilities @TimidRobot

**Comment by tripathics** [comment]
Is this issue still open? I'm interested on solving this

**Comment by possumbilities** [comment]
@sj-jain agree I'm leaning both ways on the comma. It might be better to instead of adding the comma to increase the spacing between all the links a bit give them more visual room?

As for redoing the closing indicator the brackets are not perfect, but I'm not sure removing them makes it necessarily better. 

Moving to a discussion so others can chime in on their thoughts.

**Comment by Murdock9803** [comment]
@possumbilities Is this issue relevant now, I would like to work on it

**Comment by Cappybara12** [comment]
I agree with @sj-jain  point regarding the design of the filters. Having the letter 'x' there might blend in too much with the text, especially for first-time visitors. Using an SVG for the 'x' icon would provide a clearer visual indication of its functionality. It would not only stand out more prominently but also enhance the overall user experience. Thanks for bringing this up!
