### ISSUE TITLE
[Feature] Enhancing Thumbnail list pages

### ISSUE THREAD

**Issue by cmaguluri1305** [creativecommons/cc-resource-archive#120]
## Problem
Currently, the thumbnail pages are not designed according to the aesthetics of the current CC pages and there are also functionality issues in the pages, the thumbnail is occupying empty space on the page 

## Description
Enhancing the pages according to the current aesthetics of CC pages and working on things like semantics, and functionality improves the user experience of the thumbnail pages.

## Screenshots
<img width="1440" alt="Screenshot 2023-03-27 at 1 10 56 AM" src="https://user-images.githubusercontent.com/111651145/227800909-8f05fd95-e269-421d-9e47-11d95bd39005.png">
<img width="1436" alt="Screenshot 2023-03-27 at 1 11 44 AM" src="https://user-images.githubusercontent.com/111651145/227800919-a4117843-d9b0-42d6-b661-3f3dda1cf00b.png">
<img width="1436" alt="Screenshot 2023-03-27 at 1 12 03 AM" src="https://user-images.githubusercontent.com/111651145/227800929-926deb02-5a50-49ae-a3e5-ae9a37006ba0.png">

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
Hey @cmaguluri1305,
Could you provide a description of the results you wish to obtain? or the exact functionality you wish to change?
It's always a better practice to mention precisely about the problem and the expected solution.

**Comment by justaskulkarni** [comment]
These are resource pages. Thumbnail list is a part of Home and See All pages.

**Comment by possumbilities** [comment]
I woud agree with @justaskulkarni to move discussion to those other Issues.

**Comment by cmaguluri1305** [comment]
@possumbilities will lookout for other issues👍
