### ISSUE TITLE
[Bug] Add HTML lang attribute to HTML files

### ISSUE THREAD

**Issue by JennySimen** [creativecommons/cc-resource-archive#128]
## Description
The HTML files do not contain an HTML lang attribute which is neccessary because it helps search engines  to return language-specific results on the SERP.

## Reproduction
Open to the HTML files

## Expectation
This will help to improve the interpretation of the page content by users in different locales.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by sj-jain** [comment]
@JennySimen good idea , this may be especially helpful in choosing language filters by users 👍, also making it universally accessible . i am interested in fixing this issue . for more you can see discussion in #87

**Comment by Ipshita02** [comment]
@JennySimen I would like to work on this please assign this to me.
