### ISSUE TITLE
[Feature] Changing href of main logo

### ISSUE THREAD

**Issue by cmaguluri1305** [creativecommons/cc-resource-archive#134]
## Problem
As there's already an open issue #97 I'd like to add to it. When the user clicks on the logo of the webpage it redirects to `https://creativecommons.org/` instead of reloading the archive page which is not good navigation, so my view is that when we click on the logo we should get reloaded archive page and there should be a button "about us" which redirects to `https://creativecommons.org/`.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
Hey @cmaguluri1305 ,
Nice catch. The idea of reloading the page archive page is pretty reasonable, you can check out issue #68 as it also focuses on a similar idea.
The second part which is "about us button" is already fixed in the issue #68 by @adidevs.

**Comment by arifhossain512** [comment]
is this implementation already done or not?

**Comment by adidevs** [comment]
Hey @cmaguluri1305 , this is indeed a good issue to put forward. Also, it can be better to change the logo altogether and create a new one for the CC Resource Archive if the maintainers agree to the same. This shall improve the site aesthetic and UX.

Also, the "Creative Commons Resource Archive" header shall be definitely be refactored in the Vocabulary migration and it is then that the logo can be updated along with the href. We can consider an interim solution until then I guess.

**Comment by possumbilities** [comment]
I'm closing this and suggest any further convo move to the other mentioned Issues here :)
