### ISSUE TITLE
[Feature] Remove underline from links. Change "submit resource" and "See all" into <button>

### ISSUE THREAD

**Issue by Aditya-ahirwar** [creativecommons/cc-resource-archive#135]
## Problem
Links on the page have underlines which don't looks good. Also "submit resource" and "See all" should be button tags.

## Description
Links on the page have underlines which make the page look crowded. We can remove these underlines to make the page look good.
 "submit resource" and "See all" should be button tags to enhance user experience.

## Implementation
- [x ] I would be interested in implementing this feature.

**Comment by Ipshita02** [comment]
I think I can do this. please assign me

**Comment by possumbilities** [comment]
Hi! Thank you for taking the time to write these, but generally links should have underlines to be adequately accessible. The "see all" is a link, which loads a new page. Buttons are for changing the state of an existing page in some way, links/anchors are for opening new pages so I'd say that it seems like both of these items aren't Issues at the moment. ❤️

**Comment by Ykumar1415** [comment]
if this issue not solved then can I work on this

**Comment by nandu-99** [comment]
@possumbilities I would like to take ownership of the task to convert the "submit resource" and "see all" links into buttons. Enhancing them with CSS features such as borders, shadows, border radius, and subtle transitions would improve their visual appeal and usability. Please assign this task to me so I can begin working on it.
