### ISSUE TITLE
[Feature] Add footer to the page.

### ISSUE THREAD

**Issue by Aditya-ahirwar** [creativecommons/cc-resource-archive#136]
## Problem
The page doesn't have any footer.

## Description
The https://resources.creativecommons.org has no footer but the main website https://creativecommons.org/ has. By adding a footer we can add information like copyright, contact, privacy policies, and terms and conditions. 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
Hey @Aditya-ahirwar,
It's great to see your enthusiasm for making a contribution, but issue mentioned above has already been addressed here #34. I suggest you to close the issue for now and carry the conversation here #34.
