### ISSUE TITLE
[Feature] <a> in the "header.html" file tag is convering whole header. 

### ISSUE THREAD

**Issue by Aditya-ahirwar** [creativecommons/cc-resource-archive#140]
## Problem
The <a> tag in the "header.html" file is covering the whole width. 

## Description
The <a> tag in the "header.html" file is covering the whole width. It navigates to http://creativecommons.org/ on clicking anywhere on the header which isn't correct. We should navigate to http://creativecommons.org/ only by clicking the logo.

## Alternatives
To implement this all we need to change is:
In header.html 
`<a href="//creativecommons.org/"><div id="bannercc"></div></a>`
![Screenshot before 2023-04-01 105436](https://user-images.githubusercontent.com/77871976/229267369-37306a16-4be7-4aa3-b9b5-e12616c66931.png)

To
`<a href="//creativecommons.org/" style="display:inline-block;"><div id="bannercc"></div></a>`
![Screenshot after 2023-04-01 105655](https://user-images.githubusercontent.com/77871976/229267380-22a538b2-ffa9-473d-b086-c878cca7825a.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by codin-AWMKAR** [comment]
Kindly Assign This Issue to Me i will be happy to help.

**Comment by Lakshay-Pruthi** [comment]
@Aditya-ahirwar Great finding but this issues is same as #70 . Please go through [contribution guidelines](https://opensource.creativecommons.org/contributing-code/) if you haven't.

**Comment by Aditya-ahirwar** [comment]
Thanks for letting me know. I will close this issue.
