### ISSUE TITLE
[Bug] Language filter overlapping with Resource cards

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#147]
## Description
After the new code merges, the languages are overlapping with the resource card after clicking see all.

## Reproduction

1. Go to https://resources.creativecommons.org/all/
2. See error

## Expectation
A margin/padding can provided which can fix this overlapping.

## Screenshots
See the Language filter

<img width="286" alt="Screenshot 2023-04-01 at 6 05 33 PM" src="https://user-images.githubusercontent.com/77684943/229289081-142f10fa-8a20-4de3-9e82-8ef7ef602b87.png">

## Environment

 - Device: Laptop
 - OS: MacOs
 - Browser: Firefox
 - Other info: All resolutions

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Lakshay-Pruthi** [comment]
@Xaid-vfx Could you share environmental details such as screen resolution, browser etc ? it is working completely fine on my pc
![image](https://user-images.githubusercontent.com/91469717/229292020-74062b9f-46b3-4943-ae7e-cf18e7b2500a.png)

**Comment by Xaid-vfx** [comment]
@Lakshay-Pruthi I think the above issue persists in **Firefox for all resolutions**. It works fine on Chrome and Safari.
Regardless of browser, I think it would be appropriate to provide some space between Cards and Filter. Even in chrome, the space is too little. A little margin would fix the issue for all browsers.

**Comment by yogeyyy** [comment]
Hey @Xaid-vfx , 

Since "Submit a resource" link is added, I don't think this issue persists. I might be wrong though. Lemme know your thoughts :)

**Comment by Ajay-singh1** [comment]
@TimidRobot Can we close this issue now?

**Comment by Murdock9803** [comment]
@possumbilities The issue gets resolved by the PR #316 and can be closed successfully 🙌
