### ISSUE TITLE
[Feature] Adding a new Chat Assistant 

### ISSUE THREAD

**Issue by aayushchauhan10** [creativecommons/cc-resource-archive#153]
## Problem
If a user is stuck in something on the website or if the user wants to know something about the organization and other details about the website at a single place.

## Description
This is a chatbot created in HTML, CSS and JavaScript to help the user if it wants to get some information or want to an assistant of CC organization. It will generate automated replies on behalf of the organization to give help to the user.

## Alternatives
In contrast to other paid software that is available online but only has a limited capacity, such as providing users with thousands of texts for free and then organization has to pay to use them, but this chat assistant was entirely constructed from scratch and will produce responses to user questions. As a result, it has the benefit of being original.

## Implementation
I already wrote its HTML, CSS and JavaScript and it only needs some questions to be edited according to organization before fully deployed, and as I am a new to Docker, so, I tried to implement it but could not do so because it was not getting shown on the browser while using docker. So, if you select me in the project "Modernize CC Resource Archive", after doing all the modernization of the website provided in the project, I would also be interested in implementing this feature in your guidance. @possumbilities @TimidRobot 
Thank you!
I also provided some screenshots by implementing it in a single webpage that How it will look on the website.
1.
![1](https://user-images.githubusercontent.com/121094312/229298144-ad71e512-c1b7-45d3-a8c9-f42409d3fab0.png)

2.
![2](https://user-images.githubusercontent.com/121094312/229298176-14b2ed71-6d31-4fa5-ae83-9887cd15c7a3.png)

3.
![3](https://user-images.githubusercontent.com/121094312/229298196-abf51202-ab0a-4041-8978-4a27d374efaa.png)[

4.
![4](https://user-images.githubusercontent.com/121094312/229298206-df3ff629-b465-4fa9-b62d-788855f8d911.png)

**Comment by Xaid-vfx** [comment]
Hey @aayushchauhan10,
It's a great idea to use a chatbot for answering questions, but currently it falls out of scope for this project. It will just add more complexity to the project. About answering questions for users, I think a better approach would be to put some FAQs just like [cc-chooser](https://chooser-beta.creativecommons.org/).
However, I think a better option would to pitch this idea for the main CC website. Let's see what maintainers have to say about this.

**Comment by aayushchauhan10** [comment]
Hey @Xaid-vfx,
Yes, you are right in a way that we could choose FAQs to help users but in other way, my opinion of choosing chat assistant is that if a user is stuck in some other thing that is not mentioned in the FAQs, then, there should be an option to talk with the company executive about the same, and there will be the chat assistant will work its part, but if it not there, then, it will not give the positive impression of the organization and as you said about the complexity of the project, whole of the website is just the same, we are only adding a new feature to it, so, It will not be so much complex, according to me.

**Comment by possumbilities** [comment]
Hi @aayushchauhan10 Thank you for this idea, but I think its complexity is far more from a feature standpoint than the resource archive needs. Closing.
