### ISSUE TITLE
[Bug] converting all .md resources to .html resources for uniformity

### ISSUE THREAD

**Issue by RishabhRajJoshi** [creativecommons/cc-resource-archive#159]
## Description
Some resource files are in md, and others are in HTML format. 
Converting all the files into HTML can help make code uniform. Also, HTML gives us more freedom over markdown files as we can add custom CSS in the files but not in markdown files. 

## Expectation
convert all the markdown resource files into HTML files

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Tigersteve123** [comment]
One of the advantages of having resources in .md is simplicity (lower file sizes and easier to read). It should also help with consistency because Jekyll uses the same template to render the Markdown into HTML

**Comment by yogeyyy** [comment]
Hey @possumbilities , 

I would like to work on this issue, If you can add ready to work label.
