### ISSUE TITLE
[Feature] Improve the homepage user interface for easy user experince and navigation

### ISSUE THREAD

**Issue by KrownWealth** [creativecommons/cc-resource-archive#163]
## Problem
The current UI for resource pages is good but doesn't follow all material UI guidelines which can certainly help to engage the user even more. 

## Description

![Home-Creative-Commons-Resource-Archive](https://user-images.githubusercontent.com/100444940/229366970-ccb819bb-419f-4a1a-9c77-f7a0cb812a54.png)

I will be working on enhancing the UI and following material guidelines for both the homepage and other sub-pages. Modernize the cc-resource-archive by adding some Internal Design Systems (Vocabulary) to the homepage UI. Addition of a readable hero-banner, redesigning of the resources cards, and designing of a new footer in correspondence or the Creative Commons main website.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by justaskulkarni** [comment]
@KrownWealth the issue that you have raised contains several points which have already been raised as issues. I appreciate your enthusiasm but it'd be better if you share your ideas in those individual issues rather than raising one big issue.

**Comment by KrownWealth** [comment]
@justaskulkarni thanks for your response. I'm new to the world of open source. I mean no offence. And thanks for your advice. But I would like to know if I should just delete the issue since someone else has opened it earlier than mine.

**Comment by justaskulkarni** [comment]
@KrownWealth I'd say leave the final decision to the maintainers. If they feel that this is a separate issue then they might change the label to ticket work required otherwise they'll discard it.

**Comment by KrownWealth** [comment]
Alright. Thanks for your swift response.

**Comment by Rbcoder1** [comment]
Can I Work On IT

**Comment by kmr-sahil** [comment]
I can contribute in this by developing a better UI out of it, could you please assign me.

**Comment by BalrajDhakad** [comment]
Hey,
I am Balraj,
I am willing to work on this issue
