### ISSUE TITLE
[Feature] Add a section heading to the resource cards

### ISSUE THREAD

**Issue by KrownWealth** [creativecommons/cc-resource-archive#165]
## Problem
I noticed there is no heading added to the resource cards on the homepage. This might give a user some kind of different random meaning or interpretation of which section it is or what the cards stand for. 

![resourceCard](https://user-images.githubusercontent.com/100444940/229529270-a0bbed42-5aa5-4119-844a-acd6346d38e0.png)

## Description
 I would like to add a section heading to the cards as it is seen on the featured projects in the [opencource.creativecommons.org](https://opensource.creativecommons.org/)

![featuredResources](https://user-images.githubusercontent.com/100444940/229529255-54ce4bd8-2a82-4ae4-b5d2-b2a0d7150b36.png)

## Implementation
- [x ] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
This would actually be quite good. Just a quick advice (you might have already considered) to add the heading in the `_layouts(listing.html)`, as it would then be visible for both landing page and all.html.

**Comment by Ykumar1415** [comment]
I would be interested in implementing this feature.

**Comment by SamarthShukla17** [comment]
I would be interested in implementing this feature.

I was thinking, what could be the heading though??
