### ISSUE TITLE
[Feature] Fix the mobile responsiveness for the website

### ISSUE THREAD

**Issue by KrownWealth** [creativecommons/cc-resource-archive#166]
## Problem
Currently, when a user views the website on a mobile device or screens it displays shrinkage with no clear text and graphics. This reduces the ability of users to clearly read what the CC resource website is all about.
 
![mobile view](https://user-images.githubusercontent.com/100444940/229558976-4c525b5e-fed4-4508-a383-a83337e2727e.PNG)

## Description
I would like to set the mobile responsiveness for the resource-archive website, thereby making the website more scalable.

## Implementation

- [x ] I would be interested in implementing this feature.

**Comment by Rbcoder1** [comment]
Can I Work On It

**Comment by Abhishek140501** [comment]
I would like to participate.

**Comment by ShivamAhir** [comment]
I am currently working on resolving this issue to ensure greater responsiveness across all devices with varying screen sizes.

**Comment by ShivamAhir** [comment]
Front page is responsive for all screen sizes. Open to make required changes.


https://github.com/creativecommons/cc-resource-archive/assets/74092725/2462607f-1ba2-45af-9970-e5bcf3db10ac


https://github.com/creativecommons/cc-resource-archive/assets/74092725/45939297-776f-472c-bb90-a77b281a7a5c
