### ISSUE TITLE
[Feature] Remove unnecessary liquid if conditions

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#170]
## Problem
There a few if statements in **listing.html** that have absolutely no use.

## Description
Lines 123,124,125 and 133
<img width="989" alt="Screenshot 2023-04-08 at 12 01 48 PM" src="https://user-images.githubusercontent.com/77684943/230707284-4d747a5b-48fd-4554-a78b-970182e9faa0.png">

Lines 146,147,148 and 156
<img width="1004" alt="Screenshot 2023-04-08 at 12 08 57 PM" src="https://user-images.githubusercontent.com/77684943/230707347-ea2a5ea1-51bb-4c90-a264-94ef33a9f861.png">

The variables **topicfilter**,**languagefilter** and **mediumfilter** here are not initialized anywhere, so they will always be null and these conditions will always be true.
Ideally, these lines were supposed to filter the resources cards based on the value stored in the variables **topicfilter**,**languagefilter** and **mediumfilter**. Since these variables are not initialized anywhere, these conditions become useless.
Filter process is now done using `display: block & none` over resource cards, so these statements have no use.

## Additional context

To reproduce this, just delete these statements and verify the functionality of the website.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
@Samim-Aktar-coder it's not yet approved

**Comment by wisekiran** [comment]
Hi, I removed the the unnecessary liquid if conditions and created a pull request https://github.com/creativecommons/cc-resource-archive/pull/211
Please review.
