### ISSUE TITLE
Remove underline from the list items in resourcenavbar and make the Submit Resource look like a Submit button

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#173]
## Description
The list items in the resourcenavbarhave underline which looks odd. The Submit resource hyperlink can be made to look like a button.

## Reproduction

1. Go to [Creative Commons Resource Archive](https://resources.creativecommons.org/)

## Expectation

Remove underline from the list items in resourcenavbar and make the Submit Resource look like a Submit button

## Screenshots

Before:
![ccb](https://user-images.githubusercontent.com/62856848/233365707-909203d0-dda6-4f03-b625-f5601c0e6e8a.png)

After:
![ccs](https://user-images.githubusercontent.com/62856848/233366073-078c2ff3-6c64-403e-8047-d0a184954d65.png)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Xaid-vfx** [comment]
Same as #135. Check @possumbilities [comment](https://github.com/creativecommons/cc-resource-archive/issues/135#issuecomment-1492480714) there.

**Comment by NIKHIL95969** [comment]
@possumbilities can I start work on it

**Comment by possumbilities** [comment]
Closing see comment above: https://github.com/creativecommons/cc-resource-archive/issues/173#issuecomment-1519014908
