### ISSUE TITLE
[Bug] The logo is not properly aligned for small devices

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#183]
## Description
When switched to smaller screens, the Creative Commons logo gets partially hidden because of poor padding around it.

## Reproduction
1. Go to https://resources.creativecommons.org/
2. right click and go to inspect element.
3. make the width of the screens smaller. 
4. For every decrease in width, The logo gradually slips out of the page.

## Expectation
The page should have some padding on the top So that the whole logo becomes visible.

### Before :
![Screenshot 2024-01-10 145636](https://github.com/creativecommons/cc-resource-archive/assets/136724527/88c2e738-bf8f-497c-b397-78f1ecd550f8)

###After :
![Screenshot 2024-01-10 150838](https://github.com/creativecommons/cc-resource-archive/assets/136724527/4eb62a5f-7ced-4596-a7e2-2ab62b29e008)

## Additional context
The sliding bar at the top named `Explore CC` also needs to be positioned correctly according to the padding at the top.

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by Soumya1869** [comment]
@Murdock9803 is this issue still open?

**Comment by BalrajDhakad** [comment]
Hey,
This is Blaraj,
and I am willing to work on this issue,
can you please guide me.

**Comment by Murdock9803** [comment]
hello @BalrajDhakad, the issue has not been approved yet, So we should wait while making any contributions. Also, I already made a PR which solves the issue, you can check that

**Comment by BalrajDhakad** [comment]
Okay,
thanks,
Can you suggest me some other issue similar to this one that I can do a job of contributing

**Comment by possumbilities** [comment]
Anyone that wants to try to correct this, please do so.

**Comment by Murdock9803** [comment]
I previously made a PR which was closed as the issue wasn't approved. I would like to take up this again

**Comment by Murdock9803** [comment]
Thanks everyone !
