### ISSUE TITLE
[Bug] Resource Images are acting as a Link

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#197]
## Description
For the resources that does not contain a video, the resource images are acting as Link and is occupying the entire screen width. This makes the even the blank area acting as a clickable link.

The reason behind this is that anchor tag encloses the background image tag which has a `margin: auto` property, making it occupying the entire screen width.

<img width="453" alt="Screenshot 2024-03-05 at 9 26 55 PM" src="https://github.com/creativecommons/cc-resource-archive/assets/77684943/b71fce83-106b-44c4-88fc-8069d681695a">

## Reproduction

1. Go to https://resources.creativecommons.org/get-cc-savvy/
2. Hover the pointer on resource image
3. Hover the pointer on left and right side of this image (this blank area should not be clickable)
4. See error.

## Expectation
There can be two resolutions for this bug:

- Either remove the `margin: auto` property and center the image using a flex box or any other method.
- Or Removing the href link from resource image since we already have a visit button below which directs to the same link.

## Screenshots

<img width="1143" alt="Screenshot 2024-03-05 at 9 33 44 PM" src="https://github.com/creativecommons/cc-resource-archive/assets/77684943/360afce8-4971-4d72-be6a-e741b10b16c8">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
I think removing the link entirely is a better solution since the link is already present. So long as there's not unforeseen side effects that's likely the better option.

**Comment by possumbilities** [comment]
@SamarthShukla17 feel free to

**Comment by SamarthShukla17** [comment]
@possumbilities can you help me with the file that is needed to be worked with in order to solve this issue. (I cannot find the code in the repo).

**Comment by Artemis6161** [comment]
intall Docker

**Comment by SamarthShukla17** [comment]
I am running the command: docker compose up 
(I have docker installed)
<img width="960" alt="image" src="https://github.com/creativecommons/cc-resource-archive/assets/151535429/2125dfd7-de64-40e7-aeda-15e591d0b6fc">


and on clicking http://0.0.0.0:4000, I am getting this page:
<img width="960" alt="image" src="https://github.com/creativecommons/cc-resource-archive/assets/151535429/8db9573e-df4d-4aa3-ba21-ef56d343e2e2">

Can anybody help me eith this?

**Comment by possumbilities** [comment]
@SamarthShukla17 localhost should be 127.0.0.1 not 0.0.0.0 (which is essentially a wildcard). You're on Windows it looks like. 

Since this is off-topic: I'd suggest moving this to a new Issue, unless there's one already created for it (look first).

**Comment by yogeyyy** [comment]
@possumbilities I have raised a PR which fixes this issue. Please review my PR, and provide feedback (if any). 
Thanks

**Comment by SamarthShukla17** [comment]
Thanks @possumbilities , @TimidRobot and @Artemis6161 for the clarification, it helped me a lot.

**Comment by SamarthShukla17** [comment]
@possumbilities I have successfully resolved the bug by removing the link from the resource image and have created a PR [#214] for the same. Kindly review it and provide me your valuable feedback. Thanks.

**Comment by Artemis6161** [comment]
[possumbilities](https://github.com/possumbilities) Thank you for clarifying my droughts.it was so helpful.
