### ISSUE TITLE
[Feature] Explore CC Header is sliding upon other elements

### ISSUE THREAD

**Issue by FZehra1512** [creativecommons/cc-resource-archive#207]
## Description
The Explore CC header on the [resources.creativecommons.org]( https://resources.creativecommons.org/) page is not styled in the similar way as on [creativecommons.org](https://creativecommons.org/) page. On Resources page the header is sliding upon other elements below it, and this behaviour is different from that on creativecommons.org page, where, the sliding down of the header moves down all elements below it. The behaviour and stylings of this Header should be uniform across all web pages of Creative Commons.

## Screenshots

[**resources.creativecommons.org**]( https://resources.creativecommons.org/) 

![image](https://github.com/creativecommons/cc-resource-archive/assets/142977761/cc3cf153-095e-497b-814b-c0b7d06b1cc3)

[**creativecommons.org**](https://creativecommons.org/)

![image](https://github.com/creativecommons/cc-resource-archive/assets/142977761/0f6d1b2d-d809-4fe2-98c9-79caf4fdcfb0)

## To Reproduce
- Visit  [resources.creativecommons.org]( https://resources.creativecommons.org/) and click on Explore CC button.
- Observe the sliding behaviour.
- Visit [creativecommons.org](https://creativecommons.org/) and click on Explore CC button.
- Observe the sliding behaviour.

## Alternatives
The header's position could simply be changed from `position: absolute` to `position: relative` for the required behaviour along with changings in some other properties. For uniformity some additional stylings could also be changed e.g. Font Size.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by FZehra1512** [comment]
Hi! @possumbilities i created this issue to improve a minor detail, let me know if you think it needs to be improved

**Comment by FZehra1512** [comment]
Thanks @possumbilities, I will create a PR as soon as possible

**Comment by Artemis6161** [comment]
I have made the changes, please review this PR. Thankyou

**Comment by FZehra1512** [comment]
Hi @possumbilities, I created the PR #209 for this issue. Can you please review it, if it resolves the issue?
