### ISSUE TITLE
Utilize organization default community health files

### ISSUE THREAD

**Issue by nox1134** [creativecommons/cc-resource-archive#218]
## Description
Remove duplicate files(CODE_OF_CONDUCT.md, CONTRIBUTING.md) from the repository to ensure alignment with organizational defaults as outlined in GitHub Repo Guidelines.
Also update the readme file.

Related to:
(https://github.com/creativecommons/.github/issues/38)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by BalrajDhakad** [comment]
In this issue I am not able to understand what files are duplicate.

**Comment by nox1134** [comment]
Hi @BalrajDhakad!
Several repositories contain duplicate files that match the organizational defaults:
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Please remove these files and update the Readme to direct to new links. You can consult this issue (https://github.com/creativecommons/.github/issues/38) and review the other referenced issue for guidance. Ensure similar changes are made accordingly.

**Comment by kushchoudhary98** [comment]
Ok guys it's done. Can you please review it, if I have done it right.
