### ISSUE TITLE
[Bug] Overlapping Text in Languages list on Home Page

### ISSUE THREAD

**Issue by praveen-rikhari** [creativecommons/cc-resource-archive#223]
## Description
In the Languages list on the home page, the list items for Armenian and Russian languages are overlapping each other, which can cause readability issues and potential confusion for users and hence not approaching towards a better user experience.

## Reproduction
1. Go to https://resources.creativecommons.org/
2. In the languages list you can observe the overlap between Armenian and Russian language text.

## Expectation
Each language listed in the Languages section should be displayed clearly and distinctly, without any overlap or interference from other languages.

## Screenshots
![Screenshot from 2024-03-19 17-42-13](https://github.com/creativecommons/cc-resource-archive/assets/84331681/d2cd11e6-59fc-4bb3-90f9-91c1fbe45f76)

## Environment
 - Device: (laptop)
 - OS: (Ubuntu 20.04)
 - Browser: (Firefox)
 - Version: (122.0.1)
 - Other info: (checked in all the screen sizes/zooms)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by BalrajDhakad** [comment]
I am willing to work on this issue @possumbilities

**Comment by Xaid-vfx** [comment]
@praveen-rikhari I am not able to reproduce this issue, tried all screen widths and browsers

**Comment by praveen-rikhari** [comment]
@Xaid-vfx Thanks for your consideration.Did you tried on `FireFox` as I alredy mention in the `Environment` section of issue that I am using `FireFox` browser

**Comment by Xaid-vfx** [comment]
> @Xaid-vfx Thanks for your consideration.Did you tried on `FireFox` as I alredy mention in the `Environment` section of issue that I am using `FireFox` browser

Yeah I tried firefox along with some other browsers, still not able to reproduce. 

<img width="637" alt="Screenshot 2024-03-22 at 10 28 50 PM" src="https://github.com/creativecommons/cc-resource-archive/assets/77684943/b8f7a4bb-5d2d-40dc-9cb7-40ea0bcbc712">

**Comment by praveen-rikhari** [comment]
Hey @Xaid-vfx  Thanks for your feedback! While the overlapping text issue may not be apparent on your Firefox browser, it seems to be more prevalent on Linux systems. I've consistently encountered it on Firefox in Linux. I've also tested it on another Linux system with Firefox to recheck. . If you're interested, trying it out on a Linux setup might shed more light on the issue. Let me know if you need further assistance. Appreciate your attention to this matter!
