### ISSUE TITLE
Submit a resource button 

### ISSUE THREAD

**Issue by Cappybara12** [creativecommons/cc-resource-archive#226]
## Description
Enhance the visual design of the "Submit a Resource" button to align with the website's theme and improve user engagement. Although the issue is listed in #161 I wanted to highlight the implementation as well

## Additional context
Attached is a GIF demonstrating the planned implementation of the improved "Submit Resource" button design

## Implementation
![Home_CreativeCommonsResourceArchive-GoogleChrome2024-03-2015-00-10-ezgif com-video-to-gif-converter](https://github.com/creativecommons/cc-resource-archive/assets/122734275/cc2ee931-65c2-4c40-9013-eb9675595bd2)

- [x] I would be interested in implementing this feature.
## Design Details 
The design of the button is intended to signify the idea of submission, with an arrow icon that appears when hovering over it. This visual cue enhances usability and intuitively communicates the button's purpose to users and counters the <a> tag discussion in  issue #135

**Comment by possumbilities** [comment]
Thank you for your contribution! Please don't open new Issues, when existing ones exist that can be expanded.

Closing as duplicate.
