### ISSUE TITLE
Enhance Navbar Onclick Functionality

### ISSUE THREAD

**Issue by Cappybara12** [creativecommons/cc-resource-archive#227]
## Problem
The onclick functionality in the navbar currently reflects on the entire section, causing disruption in navigation.
## Description
Improve the onclick functionality in the navbar to prevent reflection on the entire section, ensuring smoother navigation.While a similar issue (#70 ) has been raised previously, this issue aims to provide additional context, code snippets, and improvements to enhance the ease of contribution for contributors.

## Additional context
Attached is a video demonstrating the improved onclick functionality in the navbar. Additionally, a screenshot of the updated code snippet is provided for reference. 

![Home_CreativeCommonsResourceArchive-GoogleChrome2024-03-2015-46-57-ezgif com-video-to-gif-converter](https://github.com/creativecommons/cc-resource-archive/assets/122734275/4928a976-20ae-4ca1-a284-f61a73017012)
<img width="419" alt="Screenshot 2024-03-20 154642" src="https://github.com/creativecommons/cc-resource-archive/assets/122734275/e2db364b-e22c-40d4-b91e-dc184ac7c6f6">

## Implementation
Update the onclick event handler to target specific navbar elements.
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@Cappybara12 Thank you for your enthusiasm! ❤️ 

It would be better to expand on #70, rather than open a new issue. It helps keep things in the same place so they can be discussed and approved. 
Please try to add to existing issues if they already exist.

**Comment by Cappybara12** [comment]
Ok I will keep this in mind
