### ISSUE TITLE
[Feature] Include the footer in the submission and in the resource view

### ISSUE THREAD

**Issue by vivitt** [creativecommons/cc-resource-archive#242]
## Description
After the work done in https://github.com/creativecommons/cc-resource-archive/pull/206, the site already includes the footer on the homepage. Now, the footer can also be included in the submission and resources view to add visual consistency over the entire site, and ease the navigation. 

The code that implements the footer currently included in [listing.html](https://github.com/creativecommons/cc-resource-archive/blob/main/docs/_layouts/listing.html) can be extracted to a new footer.html file. Then, it will be possible to leverage the [Jekyll includes folder](https://jekyllrb.com/docs/includes/) to easily add the footer to any other view on the site.

## Alternatives

An alternative to this option would be to include the footer only in the resources view, taking into account that currently the submissions view has not so much content which can led to a weird visual effect.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Murdock9803** [comment]
@vivitt 
As the issue is now `ready for work`, Are you working on this ? I would be glad to help

**Comment by BalrajDhakad** [comment]
I will also be glad to contribute to this issue.

**Comment by vivitt** [comment]
Hi @Murdock9803 and @BalrajDhakad, thanks for asking. I already had the changes made so I just opened a [PR](https://github.com/creativecommons/cc-resource-archive/pull/264)
