### ISSUE TITLE
[Feature] Add CC header to resource and submission pages

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#271]
## Problem
The `resource` pages and `submission.html` pages do not have the standard header for creative commons resource archive

## Description
Addition of a header improves navigability and consistency across the sites.

## Additional context
The use of CC internal design system (vocabulary) can help with the implementation of standard header for the pages.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Murdock9803** [comment]
@sachan13harshit The issue is not yet ready for work, as you can see at the labels. Hope that helps 🙌

**Comment by nandu-99** [comment]
@Murdock9803 can you pls describe more about the issue?

**Comment by Murdock9803** [comment]
@possumbilities When we discussed about the issue, as far as I remember we thought of letting the header as it is without any links ?
I believe we can discuss it here further, about what links to be added in the header nav ?
Do share your thoughts @nandu-99 and everyone !

**Comment by possumbilities** [comment]
@Murdock9803 It may be that a recent PR you've done satisfies this, and it got missed, and just needs to be linked and then this closed as resolved.

**Comment by Murdock9803** [comment]
@possumbilities  I believe the issue can be linked to the PRs #304 and #315.

**Comment by possumbilities** [comment]
@Murdock9803 Based on that I'd say work in the following PRs resolves this, closing.
* #302
* #304
* #315
