### ISSUE TITLE
[Feature] Add a video guide for manually submitting resources

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#275]
## Problem
The resource submission process is not very intuitive for someone who is not familiar with github. There are many people who want to submit resources but might find it difficult to do so without a guide.

## Description
The Implementation of a to-the-point step-by-step video guide can be very helpful for the users who find it difficult to read documentation. Also, it saves a lot of time.

## Alternatives
An alternative can be including a step-by-step written guide for the process, but I prefer both the methods to be included in the resource page. 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
We opted to stick with text only instructions for accessibility and clarity.
