### ISSUE TITLE
[Feature] The logo should be in bold letters like others sites

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#294]
## Problem

The current logo of [resource archive](resources.creativecommons.org) is in light font, whereas other sites have their logo in bold letters. This can be seen in sites like [Open Source](https://opensource.creativecommons.org/) website.

## Description

Making the logo bold will maintain consistency across sites and provide a better view.

## Additional context

The logo of Resource Archive site:
![Screenshot 2024-06-29 163709](https://github.com/creativecommons/cc-resource-archive/assets/136724527/347128bf-5955-4746-a21c-3d868d25d83d)

The logo of Open source site:
![Screenshot 2024-06-29 163726](https://github.com/creativecommons/cc-resource-archive/assets/136724527/97451a6e-1fa2-4362-8e3e-81a70f1a23e6)

The logo of main site:
![Screenshot 2024-06-29 163637](https://github.com/creativecommons/cc-resource-archive/assets/136724527/577a4922-2074-4e1e-b8cd-6fccbc79f6a6)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by nandu-99** [comment]
@Murdock9803 I want to work on this issue

**Comment by sanjanaynvsdl** [comment]
Hey @Murdock9803,
I would like to work on this issue!

**Comment by Spoorthy1423** [comment]
Hey!! @Murdock9803 i would like to work on this issue, can u please assign me ...

**Comment by Ajay-singh1** [comment]
Good first issue.

**Comment by Ajay-singh1** [comment]
> Hey @Murdock9803,
> I would like to work on this issue!

Feel free to open a PR.

**Comment by Murdock9803** [comment]
With the implementation of new design, all CC sites will move towards vocabulary. So, the issue is irrelevant as any change in the header should be done directly to the vocabulary 🙌 
Closing for now.
