### ISSUE TITLE
[Feature] Add "Infographic" to the documentation about media in  resourcetemplate.md

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#299]
## Problem

For the submission of resources, in the `resourcetemplate.md` file, there is a description about available options to choose from, for the `medium` of resource. But there are total 5 options documented. At present there are total of six options available.

## Description

Including the `Infographic` option will help the users to categorize the resource properly and will also be significant, as we already the option in our site. It is just not included in the documentation.

## Additional context

The current resource template file can be accessed [here](https://github.com/creativecommons/cc-resource-archive/blob/main/resourcetemplate.md)
On line 76 of the file, there is description of the medium category. there are 5 options present.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Dipti0704** [comment]
hey @Murdock9803 can you please assign this issue to me?

**Comment by poojatalele** [comment]
I would like to work on this, kindly assign.

**Comment by possumbilities** [comment]
@lokendra005 If you comment here I can Assign you!
