### ISSUE TITLE
[Bug] Language List Columns Collapsing on Website

### ISSUE THREAD

**Issue by nandu-99** [creativecommons/cc-resource-archive#306]
## Description
 I have encountered an issue on our website where the list of languages is not displaying correctly. Specifically, the two columns of language names are collapsing into each other, causing a poor visual layout and readability issue

## Expectation
The list is supposed to be in two columns.
The columns are currently overlapping, making it hard for users to read the language names clearly.

## Screenshots
<img width="254" alt="Screenshot 2024-07-09 at 10 10 56 AM" src="https://github.com/creativecommons/cc-resource-archive/assets/145771776/66b53b2b-a82e-47a5-82c6-48e60c6d7c45">

## Additional context
I would love to resolve this issue as soon as possible to ensure a seamless user experience. Your prompt assistance in fixing this would be greatly appreciated.

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@nandu-99 good spot!

**Comment by nandu-99** [comment]
@possumbilities Thank you
