### ISSUE TITLE
[Bug] The thumbnail images should have proper alt-text in listing.html

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#307]
## Description
In the `listing.html` file, there are two `<img>` tags present with class `thumbnail`. The image tags do not have an `alt` attribute specified. This needs to be corrected for all the resources with suitable text in `alt` attribute.

## Reproduction

1. Go to the codebase at https://github.com/creativecommons/cc-resource-archive.
2. Open the `listing.html` file in `docs/_layouts/listing.html`.
3. Scroll until the `<img>` tags inside `#thumbnaillist`.
4. See error.

## Expectation
The resources should have corresponding suitable `alt` attributes inside the `<img>` tag.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by lokendra005** [comment]
@possumbilities can you assign this issue to me

**Comment by Murdock9803** [comment]
@lokendra005 You can move forward with raising a Pull Request and then it will be assigned to you if the issue gets resolved 🙌

**Comment by Murdock9803** [comment]
Since multiple people tried to solve the issue, and lacked some minute things with the PRs, here is some more context about the process we are aiming to follow, as per @possumbilities : https://github.com/creativecommons/cc-resource-archive/pull/328#issuecomment-2391531317

**Comment by Queen-codes** [comment]
Hi @possumbilities. Dropping a comment so it can be assigned to me. Thank you for your patience and guidance when I initially opened a PR for this. @Murdock9803 Thank you for your help too
