### ISSUE TITLE
[Bug] html markup contains inline styles

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/cc-resource-archive#311]
## Description
Various `.html` files make regular use of inline styles. EX: `<div style="font-size: 1.4em;">`.

## Expectation
All styles should be within CSS files. In this case all of these inline styles should likely migrate to the `style.css` file.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by nandu-99** [comment]
@possumbilities Like can we make different css files for different html or all css should be in style.css only??, can you please clear me this, so that i can start working on this issue

**Comment by Murdock9803** [comment]
Hello, At this time only `index.html` and `all.html` pages have the inline styling as far as i remember. I am working on a PR for index and all pages.
