### ISSUE TITLE
[Bug]  Improve Mobile View Layout for Topic and Medium Columns

### ISSUE THREAD

**Issue by nandu-99** [creativecommons/cc-resource-archive#313]
## Description
In the current mobile view of our webpage, the columns for "Topic" , "Medium" , "Languages" are positioned too close to the edge of the screen, making it look crowded and potentially affecting readability.

## Reproduction
1. Open the webpage on a mobile device or resize the browser window to simulate a mobile view.
2. Observe the positioning of the "Topic" and "Medium" columns.

## Expectation
The columns should be centered and have adequate padding on the sides to improve the layout and readability.

## Screenshots
<img width="316" alt="Screenshot 2024-07-14 at 4 47 45 PM" src="https://github.com/user-attachments/assets/dd943485-b44d-4567-b08c-6ac71fac7836">

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by Murdock9803** [comment]
Good catch @nandu-99 
actually I am working on a Pull Request (halfway there) that refactors the whole code for index.html and all.html, and the result would be improved UI of homepage (including filters). It would be very nice if you find more issues like this ! 🙌
