### ISSUE TITLE
[Bug] Remove Extra White Space Between Main Content and Footer

### ISSUE THREAD

**Issue by nandu-99** [creativecommons/cc-resource-archive#314]
## Description
There is an extra white space between the main content and the footer of the webpage, which is visually unappealing and disrupts the overall layout. This space should be removed to improve the page's appearance.

## Reproduction
1. Open the webpage.
2. Scroll down to the bottom of the page.
3. Observe the extra white space between the main content and the footer.

## Expectation
The main content should flow smoothly into the footer without any unnecessary white space.

## Screenshots
<img width="1440" alt="Screenshot 2024-07-14 at 4 55 18 PM" src="https://github.com/user-attachments/assets/1e7d0a72-116e-48fe-a9bf-16206b7a3b96">

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by Murdock9803** [comment]
@nandu-99 I think the `lighter grey` is the background for the `thumbnaillist` and the main background color for the page is the white color. So the white space signifies the end of the thumbnaillist there. I would love to hear your and everybody else's thoughts as well.
