### ISSUE TITLE
[Bug] Submit a resource page - External links to github open on same page instead of new tab, nitpick: spelling of compare is incorrect

### ISSUE THREAD

**Issue by mahak-juriani** [creativecommons/cc-resource-archive#318]
## Description
On the submit a resource page - external links to github website open on same tab. Ideally should open in a new tage

## Reproduction

1. Go to home page
2. Under resources section - click on 'submit one here'
3. Click on any external link like - creativecommons/cc-resource-archive - it'll open in same tab
4. Also, nitpick: compare is written as comapre which can be clubbed with the same issue

## Expectation

External links on this page should open in new tab

## Screenshots

https://github.com/user-attachments/assets/6deeaca7-ae4f-4512-bdc5-9efbdc7bc157

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by mahak-juriani** [comment]
Respected projects maintainers - If the issue seems actionable, can I work on this as a good first issue. Thanks 🙌

**Comment by possumbilities** [comment]
@mahak-juriani Hi! and thanks for raising this. Feel free to work on this if you'd like!
