### ISSUE TITLE
[Feature] Enhance Currency Selection with Search Functionality

### ISSUE THREAD

**Issue by NayanshiSingh** [creativecommons/cc-resource-archive#322]
## Problem
Currently, the currency selection dropdown on the donate page requires users to scroll through a long list of currencies to find their desired option. This can be time-consuming and inefficient.

## Description
To improve user experience, I propose adding a search feature to the currency dropdown, allowing users to quickly search and select the desired currency.
[
![Screenshot 2024-07-26 023826](https://github.com/user-attachments/assets/e4c65ddf-d7c3-4b65-b157-aa74f923fded)
](url)

## Alternatives
An alternative solution would be to categorize currencies by regions or popularity, but this might still require users to scroll through multiple options.

## Additional context
Adding a search feature will significantly improve the user experience, especially for users from countries with less common currencies.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by NayanshiSingh** [comment]
If you find this issue(feature) actionable please do assign me this feature 
@possumbilities

**Comment by Murdock9803** [comment]
@NayanshiSingh 
The codebase for `donate` option does not lie in this repository, So I Think the issue does not belong to this repository. Would like to hear opinions on this.

**Comment by Ajay-singh1** [comment]
@Murdock9803 Yeah I think the codebase doesn't lie in this repository @NayanshiSingh Kindly close this issue.

**Comment by possumbilities** [comment]
Hi @NayanshiSingh as others have noted this functionality doesn't exist within this repository, but instead with an external service, which we don't have direct control over the dropdown in this way. Thank you for your contribution, but its not something we could implement, unfortunately.

Closing.
