### ISSUE TITLE
[Bug] Entire CC-resource-archive page is running on quirks mode

### ISSUE THREAD

**Issue by Biki-das** [creativecommons/cc-resource-archive#33]
## Description
Quite strangely the whole CC-resource-archive page is running on `quirks` mode as the `Doctype` Tag is missing from the Page, being in quirks mode can make the page not serving the modern HTML and CSS efficiently 

## Reproduction

open the CC-archive site and open the console

## Screenshots
![Home _ Creative Commons Resource Archive — Mozilla Firefox 2_24_2023 8_42_26 PM](https://user-images.githubusercontent.com/72331432/221215156-0e15c114-1f49-4f46-a606-3ff375b384ce.png)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Aditya9764** [comment]
Can  you please  assign this issue to  after posting  the solution   i want tl contribute on this project

**Comment by Neilblaze** [comment]
@Biki-das I think as long as the website runs on Jekyll, it's going to run in quirks mode, since the rendering of the pages is performed by a mixed format of YAML & markup language. Besides, the final preview is done by the DOM tree without *`DOCTYPE declaration`* hence it's going to persist anyway. Although there are a few bypasses that we can follow through, i.e. by explicitly including `http-equiv="X-UA-Compatible"` to the meta headers of the final tree.

**Comment by Biki-das** [comment]
> @Biki-das I think as long as the website runs on Jekyll, it's going to run in quirks mode, since the rendering of the pages is performed by a mixed format of YAML & markup language. Besides, the final preview is done by the DOM tree without _`DOCTYPE declaration`_ hence it's going to persist anyway (unless changed). Although there exists another bypass that one can follow through, i.e. by explicitly including `http-equiv="X-UA-Compatible"` to the meta headers of the final DOM tree of _index.html_.

I dont think so, running a jekyll website by defautl does not get me this quirks so that is surely not the case

**Comment by Biki-das** [comment]
@possumbilities this might be a small issue to fix but with high importance!

**Comment by possumbilities** [comment]
@Biki-das I think we certainly need the `Doctype` declared to align with modern standards.
