### ISSUE TITLE
[Bug] The resource pages need to be converted from `.html` to `.md` format

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#333]
## Description
The files in the `docs/_resources` contain resource pages which follow the `docs/_layouts/resource.html` layout. The files are in two different formats - `md` and `html`. This causes confusion among the contributors.

## Reproduction

1. Visit the [codebase](https://github.com/creativecommons/cc-resource-archive).
2. Go inside `docs/_resources/` folder.
3. See some files are in `html` extension and some are in `md`.

## Expectation
The files should be in a single format to maintain consistency. All files can be converted to `.md` files.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Murdock9803 Thanks for making this!

**Comment by Dev-JoyA** [comment]
Hello @possumbilities, can you please assign this issue to me . Thanks
