### ISSUE TITLE
Add a Footer to the page

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#34]
## Problem

Currently, the bottom of the page looks a bit odd. 

## Description

Adding a footer there will improve the look and feel of the page and it will also match the  current CC aesthetics

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Faizan711** [comment]
is this issue still open, if so then i would like to be assigned to work on it.

**Comment by tinniaru3005** [comment]
Hey, @Faizan711 welcome to the community thanks for your interest in contributing to the project. But the issue is not yet approved.
The issue will automatically have the status: awaiting triage label applied. Wait for a project maintainer to evaluate the issue and decide whether it's something that they will accept a pull request for.
Once the project maintainer has approved the issue and removed the status: awaiting triage label then a PR can be raised

You can go through the [Contribution Guideline](https://opensource.creativecommons.org/contributing-code/) to know more
Also as I have mentioned in the issue I would like to work on it. So you may look at the other issues.

**Comment by Faizan711** [comment]
Ok then no problem, i will find some other issue.

**Comment by tinniaru3005** [comment]
> Ok then no problem, i will find some other issue.

You can contribute by raising an issue also and once it is approved you can start working on it.

**Comment by Faizan711** [comment]
ok thanks.

**Comment by tinniaru3005** [comment]
I would love to help out someone else contribute. @possumbilities you can assign it to someone who is willing to take up the issue. ❤

**Comment by possumbilities** [comment]
@Faizan711 it's all yours!

**Comment by Faizan711** [comment]
Thanks @possumbilities.

**Comment by shreyashchandra** [comment]
Hy @Faizan711 I am also interested in working on this issue so could we collaborate on this one!!???

**Comment by Faizan711** [comment]
sure @shreyashchandra please share your ideas too

**Comment by Praveen03AJJARAPU** [comment]
Is this issue still open for development?

**Comment by Murdock9803** [comment]
@possumbilities There are no PRs opened related to this issue, And this is a very important topic - Addition of footer to the website. 
I would like to take up this issue and add the footer from search.creativecommons.org as you suggested.

**Comment by possumbilities** [comment]
@Murdock9803 Please feel free to. 

In the time that's passed since this was last created I would advise anyone doing this to model the footer after the new [creativecommons.org](https://creativecommons.org) website. It has the most current footer.

**Comment by Murdock9803** [comment]
I have been working on it, as I was assigned. Secondly, the PR opened above recently doesn't match the CC aesthetics namely font.

**Comment by Murdock9803** [comment]
@possumbilities please take a look. Thank you. 
Fonts and responsiveness have been corrected, maintaining the code scheme.

**Comment by Murdock9803** [comment]
Thanks for the guidance all along! 🙌
