### ISSUE TITLE
[Bug] Incorrect Links in Footer 

### ISSUE THREAD

**Issue by Queen-codes** [creativecommons/cc-resource-archive#350]
## Description
The HTML for the footer contains broken or incorrect links associated with the Creative Commons license. Currently, these links are set as relative paths to the codebase rather than directing users to the official links in the creative commons websites. Specifically:
- The Except where otherwise noted link points to` /policies/#license`, which leads to an error page.
- The Creative Commons Attribution 4.0 International license link points to `/licenses/by/4.0/`, which also leads to an error page.

## Reproduction

1. Open the site and go to the footer section.
2.  Click on the links in the `Except stated otherwise` paragraph
3. See error.

## Expectation
Clicking these links should lead users to valid pages about licensing, similar to what would happen if the links where clicked on the footer in the  Creative Commons Search Portal.

## Screenshots
<img width="1274" alt="Screenshot 2024-11-12 at 10 24 55" src="https://github.com/user-attachments/assets/ea21e802-1758-438b-a598-7acd9fb6e942">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Queen-codes It appears these were not localized/corrected at implementation. Good find!
