### ISSUE TITLE
Feedback and ratings

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#37]
## Problem

Currently, there is no way users can provide feedback or rate resources

## Description

Add a feature to allow users to provide feedback and rate resources. This helps users to find the best resources and also provides valuable insights for website administrators.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@tinniaru3005 Thank you for taking the time to submit this! ❤️  It's an interesting idea, but goes against the nature of the resource archive operating in a simple fashion, and creates a lot of considerations for bi-directional data flow that seems very much outside the scope of this project. While a good idea in theory, I feel that in the context of this project it's not something we'd hope to add as a feature at this time.

That said, if you feel strongly the other way and have a solid argument please feel free to comment here. In the meantime I'm closing this Issue.
