### ISSUE TITLE
[Bug] links are broken and improve files structure

### ISSUE THREAD

**Issue by Keerthivardhan1** [creativecommons/cc-resource-archive#46]
## Following links are broken

<img width="754" alt="cc" src="https://user-images.githubusercontent.com/110013820/221599721-7f936b67-ca80-4cd2-bc42-303509e478d3.png">

## Reproduction

1. visit  one of the link mentioned above 
for eg:-  https://resources.creativecommons.org/six-licenses-for-sharing-your-work/
3. click on repository
4. you will find error

## Expectation
no 404 error should occur 

## Screenshots
<img width="611" alt="new" src="https://user-images.githubusercontent.com/110013820/221600972-9efc43c3-6c3f-4043-b4ae-8cf7ba554981.png">

## Environment

 - Device: laptop
 - OS: windows 11
 - Browser: chrome 

## Additional context
Reasons for this errror:-
 destination url might be updated 
 typo error in the url .....

## Resolution
- [X] I would be interested in resolving this bug.

**Comment by Keerthivardhan1** [comment]
Visit link in https://resources.creativecommons.org/cash-music-creative-commons-portal/
is leading to bad host server error. 
Can you give me a clarity that is this the destination page of that link 
<img width="878" alt="badhost" src="https://user-images.githubusercontent.com/110013820/222066122-9a3bb85a-1e6d-4270-9676-b6f17ff17460.png">

if yes 
the problem is that , the url of the destination page has been updated
solution :
we must update the url of destination page in our code base as well 
thank you

**Comment by possumbilities** [comment]
related to #11 and likely duplicate.
