### ISSUE TITLE
[Feature] Creating a responsive Navigation bar for the site.

### ISSUE THREAD

**Issue by Faizan711** [creativecommons/cc-resource-archive#48]
## Description
This feature will display all the links in Topic, Medium and Language in the Landing page of the site in a good manner like websites of today.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@Faizan711 Hi! and thanks for this submission! ❤️ 

In general I agree with you, but before moving forward this Issue would need to contain more specifics about how you intend to implement such a plan. 

I'd also urge you to view [Vocabulary](https://github.com/creativecommons/vocabulary), our current design system, and the [Open Source website](https://opensource.creativecommons.org/) which utilizes it, and draw inspiration that would bring this site inline with that.

Moving to `ticket work required` for now.

**Comment by aaryahjolia** [comment]
@possumbilities I understand what are you asking for, As the current webpage allows only a single choice from each of the list (Topic, Medium and Language), We can just make a navbar similar to the [Open source website](https://opensource.creativecommons.org/) with 3 lists and it's sub topics. Whenever a user chooses an option from each list, We can simply write that option below the navbar with a 'cross' mark to delete that choice of option. In this manner, we can also implement multiselecting an options from each list.
I can also provide you a rough design if you are not clear about what I'm saying above. Please let me know!

**Comment by Faizan711** [comment]
Hey @aaryahjolia thanks for your suggestion, but as I mentioned I would like to work on this issue myself.

**Comment by Faizan711** [comment]
Hey @possumbilities, i saw the open source website and i can make the navigation bar for this similar to that.
It will both maintain a singular design and make it look good.
Can I start working on the issue??

**Comment by nandu-99** [comment]
can u assign this issue to me!!.... i would love to work on this issue.... i have viewed [Vocabulary](https://github.com/creativecommons/vocabulary), our current design system, and the [Open Source website](https://opensource.creativecommons.org/) which utilizes it, and drawn inspiration that would bring this site inline with that.....shall i start working on this??

**Comment by nandu-99** [comment]
@possumbilities

**Comment by possumbilities** [comment]
@nandu-99 The Issue needs to be more outlined (see above) before it's moved to "status: ready for work". If you would like to detail that here, and it goes forward I'll assign you then.

**Comment by nandu-99** [comment]
"I have an idea for improving our website's navbar, inspired by the layout on the [Open Source website](https://opensource.creativecommons.org/). My proposal is to place the logo on the left side of the navbar, with dropdown menus for topics, medium, and language on the right. I aim to make this design responsive to different devices.

To enhance this idea further, I plan to:

- Ensure the navbar adjusts well to various screen sizes for a seamless user experience.
- Optimize the dropdown menus for easy navigation and clarity.
- Maintain consistency with our website's branding to reinforce our identity.

I'm excited to work on this as my first contribution. Please consider assigning this task to me, and I'm open to any suggestions or guidance along the way."

**Comment by Artemis6161** [comment]
can u assign this issue to me. i would love to work on this issue
