### ISSUE TITLE
[Bug] Fix errors on individual resource page

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#51]
## Description

When we go to an individual resource page then it shows an error.

## Reproduction

1. Add the required content on the page

## Screenshots

https://user-images.githubusercontent.com/62856848/221657013-2db7ca88-3c7e-40f6-b1aa-5e8629c16c2a.mp4

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@tinniaru3005 This might be related to #11, and if so we should probably mark this as a duplicate and close it and move work there.

**Comment by tinniaru3005** [comment]
> @tinniaru3005 This might be related to #11, and if so we should probably mark this as a duplicate and close it and move work there.

Hey @possumbilities, we can do that.
