### ISSUE TITLE
[Bug] Use checkbox for the resourcenavtopicknown

### ISSUE THREAD

**Issue by tinniaru3005** [creativecommons/cc-resource-archive#52]
## Description

The resourcenavtopicknown currently uses list items. We can replace that with checkboxes to make the UI look better.

## Reproduction

1. The resourcenavtopicknown uses list items

## Expectation

Replace list items of the resourcenavtopicknown with checkboxes for a better look

## Screenshots

![checkbox](https://user-images.githubusercontent.com/62856848/221658062-3645396e-5b80-47d8-b46e-07691b0c6ced.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Sulochan-khadka** [comment]
since I see what all things I need to change to fix this, assign this issue to me and then I will create a PR to merge.

**Comment by possumbilities** [comment]
My concern here would be that we might end up with issues with accessibility. Thoughts from others?

**Comment by Cappybara12** [comment]
I think the x character seems a bit confusing and doesn't necessary serve the purpose . We can use ❎ instead . Here's my implementation of the same 
![All_CreativeCommonsResourceArchive-GoogleChrome2024-03-2015-00-41-ezgif com-video-to-gif-converter](https://github.com/creativecommons/cc-resource-archive/assets/122734275/f46a06cf-6900-43d1-b69d-c9725fbaffc6)
