### ISSUE TITLE
[Feature]   Add Gitpod support

### ISSUE THREAD

**Issue by Biki-das** [creativecommons/cc-resource-archive#59]
## Problem
Adding Gitpod support 

## Description
we can add Gitpod support for contributors and users to try and setup the repo fast , without taking time to locally setup if wanting to test some changes quickly and see the results

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Moving to discussion. With the advent of Code Spaces as part of GitHub what are others thoughts on this level of support?
