### ISSUE TITLE
[Feature] change the user interface of the home-page

### ISSUE THREAD

**Issue by RishabhRajJoshi** [creativecommons/cc-resource-archive#61]
## Problem
the UI of the website is outdated and does not match the cc open-source website

## Description
I have created some figma wireframes of the modifications which we can make and uniform the UIto the cc opensource UI
Please let me know if there are any suggestions or changes I can make.
If you approve the design, I can start working on their code.

## Design-1
![wrieframe-1](https://user-images.githubusercontent.com/112555922/222833053-1b1b52db-f6be-4e42-9b03-27f176594027.png)

## Design-2
![wireframe-2](https://user-images.githubusercontent.com/112555922/222833079-781c7590-529f-4942-bf8b-239d603b8543.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by iamhaider072** [comment]
I would like to contribute to this project.

**Comment by possumbilities** [comment]
@RishabhRajJoshi I'd suggest you look through the [Vocabulary](https://cc-vocabulary.netlify.app/?path=/story/hello-wip--page) design system for visual reference to follow on this.

Also live site impelmenting the system in some way: 
* https://opensource.creativecommons.org/
* https://search.creativecommons.org/

It might be reasonable for this discussion to move here more broadly?

* #79
