### ISSUE TITLE
[Feature] Reduce the download button size

### ISSUE THREAD

**Issue by Aaishpra** [creativecommons/cc-resource-archive#62]
## Problem

- Currently the download button in all the pages is very large in size, and doesn't look much appealing. 
- "[Creative Commons Licenses for Non-Profit Organizations](http://vimeo.com/84880520) from [BCcampus](http://vimeo.com/bccampus) on [Vimeo](https://vimeo.com/)", I think the placement of this content can be better.
![Screenshot from 2023-03-05 20-38-56](https://user-images.githubusercontent.com/66299533/222968798-aa10ba84-b1f4-48c9-92f9-0977fc6e9353.png)

## Description
- Reducing the size or redesigning the button can help.
- we can place the described content either in the description box or may be remove it(as there is repetition )

## Additional context
Not sure but the download button rather than downloading content just redirects to different websites or broken links.
Is this how these buttons are supposed to work?

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by codegrann** [comment]
I would like to work on this issue once approved.

**Comment by codegrann** [comment]
I don't know if other links are just broken, but one of them redirected me to a page that I could actually download the resource.
![Screenshot from 2023-03-22 08-52-03](https://user-images.githubusercontent.com/94289940/226814508-d9e1408c-24ae-4bf6-b336-15767e8b4e36.png)

**Comment by possumbilities** [comment]
Making a Discussion, since there might be routes here to upgrade the button to be inline with [Vocabulary](https://cc-vocabulary.netlify.app/?path=/story/hello-wip--page) visually and how it treats buttons.

**Comment by das123s** [comment]
Thanks @possumbilities for approving the PR of issue #62. Could you please assign me the task?
