### ISSUE TITLE
[Feature] Adding a Footer to the website

### ISSUE THREAD

**Issue by aaryahjolia** [creativecommons/cc-resource-archive#65]
## Problem/Feature description
There's a very cool footer on the open source website [https://opensource.creativecommons.org/](https://opensource.creativecommons.org/) which can be implemented in this archive's website also with some things common from the open source website **but not all** (Example: The donate button, contact section, social media links, etc). I can present a design for the footer if we can move forward with this issue.

## Implementation
- [x] I would be interested in implementing this feature.

@possumbilities Please look into this feature and give your valuable input.

**Comment by justaskulkarni** [comment]
This is same as #34
