### ISSUE TITLE
Grammatical mistakes in Readme

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/cc-resource-archive#67]
## Description
There are few grammatical mistakes in the Readme file

## Reproduction
1. Read the readme.md file
2. See error.

## Screenshots
![image](https://user-images.githubusercontent.com/91469717/223362785-d4b5a103-f4fb-4b2d-a7e7-f62f817f2245.png)
and few other missing articles.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Lakshay-Pruthi Hi and thanks for spotting this! Assigning you!
