### ISSUE TITLE
[Bug] clicking on whole header opens https://creativecommons.org/

### ISSUE THREAD

**Issue by RishabhRajJoshi** [creativecommons/cc-resource-archive#70]
## Description
The whole header div is enclosed inside the anchor tag due to which the whole header act as link but technically only the logo should act as link.

Also according to UX, clicking the logo should redirect the home page but here it is opening the CreativeCommons.org

## Screenshots

before image
![image](https://user-images.githubusercontent.com/112555922/224035024-b344657a-3c81-48ee-80e6-5cd70f539823.png)

![image](https://user-images.githubusercontent.com/112555922/224035742-1ad6bd6c-8fb6-4602-8c54-683fed6d23ac.png)

1. first remove logo from style.css and add img tag to html
2. put anchor tag across the image 

after changing the code 

![image](https://user-images.githubusercontent.com/112555922/224035965-212954f3-11e2-49da-8b0b-d434b8cab57d.png)

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.
- [x]  removing whole header as link making only the logo as link
- [x] redirecting it to the home page and not to https://creativecommons.org/

**Comment by Anju3750** [comment]
I want to work on this issue

**Comment by AdityaLahane-2003** [comment]
Hello ! I would like to contribute on this, can you assign this issue to me ?

**Comment by RishabhRajJoshi** [comment]
> Is there anyone working on this issue, I can resolve this. @RishabhRajJoshi Can you assign this issue to me?

Glad to hear that you want to contribute, but I am already interested in working on it as soon as it is assigned to me. also, I cannot assign it as I am not a mentor

**Comment by NIKHIL95969** [comment]
Could anyone help me how to start working on issue. If it not assigned me, can I work on it.

**Comment by BalrajDhakad** [comment]
I am willin to work on this issue, should I start

**Comment by Murdock9803** [comment]
@BalrajDhakad As we can see there is already a PR open to resolve this issue. Let's wait till it gets reviewed. you can work on some other issue till then

**Comment by BalrajDhakad** [comment]
Now as the PR is closed so may I start working on this issue @possumbilities

**Comment by possumbilities** [comment]
@BalrajDhakad The PR #145 is still open.

**Comment by BalrajDhakad** [comment]
Okay got it, it's my mistake

**Comment by BalrajDhakad** [comment]
Is the PR still in process? @possumbilities

**Comment by Cappybara12** [comment]
## My Implementation 
For: Update the onclick event handler to target specific navbar elements.
Attached is a video demonstrating the improved onclick functionality in the navbar. Additionally, a screenshot of the updated code snippet is provided for reference. 

![Home_CreativeCommonsResourceArchive-GoogleChrome2024-03-2015-46-57-ezgif com-video-to-gif-converter](https://github.com/creativecommons/cc-resource-archive/assets/122734275/4928a976-20ae-4ca1-a284-f61a73017012)
<img width="419" alt="Screenshot 2024-03-20 154642" src="https://github.com/creativecommons/cc-resource-archive/assets/122734275/e2db364b-e22c-40d4-b91e-dc184ac7c6f6">
