### ISSUE TITLE
Removal of unused CSS

### ISSUE THREAD

**Issue by justaskulkarni** [creativecommons/cc-resource-archive#71]
## Description

The only search result corresponding to the id greenbanner is in the style.css file.
There is no HTML div with id greenbanner corresponding to it.
![image](https://user-images.githubusercontent.com/98650743/224058003-42bba461-7d70-467e-8f1f-0eb1c7f832c3.png)
Therefore, the following piece of code is redundant:
![image](https://user-images.githubusercontent.com/98650743/224058507-5f84fb31-3989-4138-b58c-985169b335d8.png)

## Reproduction

1. Navigate to https://github.com/creativecommons/cc-resource-archive/blob/main/docs/style.css
2. Lines 114-118 form the redundant piece of code.

## Expectation

Removal of unused CSS

## Additional Context
I have tried removing the piece of code locally and confirmed to the best of knowledge that it does not affect the site in any particular way.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by justaskulkarni** [comment]
To add to my point
![image](https://user-images.githubusercontent.com/98650743/224069203-f9d19c44-494d-420d-aaaa-b9797aa10177.png)
Here, the image is as shown in the picture below:
![image](https://user-images.githubusercontent.com/98650743/224069517-7374f047-f334-4f05-b49d-f7992939e5e8.png)
Therefore, the green color of the CC logo comes from the image itself and has no relation with the id greenbanner.

**Comment by Anju3750** [comment]
I want to work on this issue.

**Comment by justaskulkarni** [comment]
@Anju3750 The issue hasn't yet been approved by the maintainers so no one can work on it at the moment. Also, I have already mentioned that I would like to resolve the issue while raising it. So I suggest that you find another issue.

**Comment by possumbilities** [comment]
@justaskulkarni Nice find, please go ahead!
