### ISSUE TITLE
[Feature] UI refinement of the website

### ISSUE THREAD

**Issue by tusharbansal22** [creativecommons/cc-resource-archive#72]
## Problem
The UI of the site is pretty outdated. Also, doesn't match with the new organisation colors of creative commons.

## Description
The issue can be solved by modernising the site's ui and also incorporating orange color in the website.

## Additional context
Here are some possible designs that can be implemented on the site
[Figma link](https://www.figma.com/file/AH74esJYUiOGg2iXjyCKdi/Untitled?node-id=0%3A1&t=V4mk1CLuoWQMhwQ6-1)

#### Design A
<img width="804" alt="image" src="https://user-images.githubusercontent.com/104081946/224292213-5fdf83ef-f091-47ce-8421-3f86d88889b3.png">

#### Design B
<img width="334" alt="image" src="https://user-images.githubusercontent.com/104081946/224292126-60e42453-45ca-4547-9554-664bc47e04fd.png">

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by Vansh-Baghel** [comment]
@possumbilities Would like to have your thoughts here as well,
Let me summarize the things which are to be improved for the website as my issue discussion has been moved here. These are the things which I feel must be added, improved and changed: 
1. Dark theme for the website : Reason is that its more comfortable for users' eyes and experience.
2. Adding better cards as @tusharbansal22 mentioned.
3. Creating dropdown navbar for the website, and replacing it with the bullet points seen at the top page of the website. 
4. To implement animations and pseudo effects for the cards : Like we could add fade in out effects which makes the website look incredible.
5. To add Footer into the website : Where people could view various social links and a CopyRight message in the end.
6. Improve content inside each card: Whenever user clicks a post, it gets directed to that post where we can download the video or watch it. This page UI also needs to be improved like changing the button style, removing unnecessary empty box, giving more distance between each boxes, etc things.
7. Submit a resource shows some error like docs.google.com refused to connect.

**Comment by possumbilities** [comment]
This is a big Issue, might be good to have a larger discussion about it.

**Comment by SamarthShukla17** [comment]
@possumbilities I would be interested in implementing this feature.
