### ISSUE TITLE
[Bug] Site not responsive on mobile screens

### ISSUE THREAD

**Issue by tusharbansal22** [creativecommons/cc-resource-archive#73]
## Description
The site shrinks to extremely small size when viewed on a smaller screen(mobile).

## Reproduction
1.  Open the [site](https://resources.creativecommons.org/)
2. Open devtools
3. Select any mobile based screen
4. See error.

## Expectation
Site should change according to screen size, but this is not the right way of responsiveness

## Screenshots
<img width="517" alt="Screenshot 2023-03-10 at 4 00 01 PM" src="https://user-images.githubusercontent.com/104081946/224293951-b4b0a5a1-077e-4667-9216-d50366c6e400.png">

## Environment
Not environment specific

## Resolution
- [x] I would be interested in resolving this bug.

Primarly, to solve the shrinking issue, adding this line 
```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
```
in `listing.html` will solve the issue.

Post that changes will be required in style sheet to modify according to mobile based screens separately

**Comment by consolexyz** [comment]
Hello, @possumbilities  can you assign this to me, i think i have the necessary skills to attempt this

**Comment by justaskulkarni** [comment]
Pretty much the same as #26

**Comment by possumbilities** [comment]
yeah, this is mostly the same as #26, likely a good idea to move discussion there.
