### ISSUE TITLE
[Feature] Organizing all the resource files

### ISSUE THREAD

**Issue by RishabhRajJoshi** [creativecommons/cc-resource-archive#74]
## Problem
All the resource pages are made inside the main docs folder where index.html , config files, gem files are present which makes it look messy 

## Description
So to organize it we can create a folder named  " _resources"  and keep all the resource pages inside it and add include and defaults in _config.yml 
I am attaching screenshot of the config code and resource folder

![image](https://user-images.githubusercontent.com/112555922/224445024-c2dff407-1bcc-452f-9e50-379251da981b.png)

## Additional context
I have tried this locally and confirmed that it does not affect the site functionality  in any particular way.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
See #95 for more info on resolution paths.

**Comment by Murdock9803** [comment]
@possumbilities I can see a PR regarding this issue opened last year. May i help reviewing the PR or it has been reviewed ?
If it contains mistakes, then I will be happy to correct them
