### ISSUE TITLE
[Feature] Improving the cards and the text

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [creativecommons/cc-resource-archive#76]
## Problem
The styling of the cards on the website isn't satisfactory, also the text looks unappealing
![image](https://user-images.githubusercontent.com/47966497/224506457-70d3edef-2ad7-4560-b4a2-20094e42a708.png)

## Description
A better styling can be achieved for the cards that navigate the user to various different sections of the resource archive, and by using a better legible font the user interface can be improved a lot. I have 2+ years of experience with developing, and styling landing pages, it's my passion and I would love to contribute.

## Alternatives
Alternative for a cards-based layout can be Search and Filter option, it would also work but cards that provide a minimum viable information, that introduces the content would prove to be a better solution as the user will get a gist, the cards can also have a Tooltip whenever the user hovers on them to provide additional required information. 
![Categories #DailyUI #day099](https://user-images.githubusercontent.com/47966497/224507208-972a28e4-1980-41d7-88d8-542bdb5f0195.png)

Tags, just like LeetCode problems have, can also help the user select a specific card that would contain relevant information.
![image](https://user-images.githubusercontent.com/47966497/224507068-00354deb-71b8-4d75-852c-e9c65f1161a8.png)

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by lonewolf1503** [comment]
@Shivangbhatnagar237  Can you please assign this issue to me?
 I wanna solve it

**Comment by Shivangbhatnagar237** [comment]
@lonewolf1503 I will be working on this issue, once it becomes ready for work

**Comment by Naman13Kumawat** [comment]
@Shivangbhatnagar237 For improving the functionality of the cards, we can also make the whole card clickable rather than just the heading and thumbnail.

**Comment by Shivangbhatnagar237** [comment]
> @Shivangbhatnagar237 For improving the functionality of the cards, we can also make the whole card clickable rather than just the heading and thumbnail.

@Naman13Kumawat yes, once a better styling of the cards is achieved then I can easily implement this functionality, but this issue pertains to the styling aspect(s) only.

**Comment by justaskulkarni** [comment]
This issue is quite similar to #25.

**Comment by Shivangbhatnagar237** [comment]
> This issue is quite similar to #25 and #35.
@justaskulkarni yes, it has some similarities but the improvement in font by changing the font-family to Helvetica, Helvetica Neue, and Souce Sans Pro (used by other CC sites), and a tooltip feature for the user to get some additional info (which might be required) is not mentioned in #25 or #35.

**Comment by justaskulkarni** [comment]
@Shivangbhatnagar237 the issue about improving the fonts is same as #49 and this has been blocked by the maintainers

**Comment by possumbilities** [comment]
I'd suggest moving these items as comments on the other issues if reasonable. closing as mostly duplicate./

Design work should follow [Vocabulary](https://cc-vocabulary.netlify.app/?path=/story/hello-wip--page), for visual reference for anyone reading this in the future.
