### ISSUE TITLE
[Bug] Href # Link on page Requires back button to be hit twice on browser

### ISSUE THREAD

**Issue by nishchay-veer** [creativecommons/cc-resource-archive#81]
## Description
After selecting the desired filters to display the resources, If I hit the back button on the browser I have to hit it twice to get back to the previous page.

## Reproduction

1. You click on any medium . Let's say "video"
2. Then you click on any language. Let's say "EN"
3. Press the back button to get back to the previous page.
4. See error.

## Expectation
It should display me all the resources that are under "video".

## Screenshots
Step1:
![issue2 1](https://user-images.githubusercontent.com/99465982/225289530-1ffa3d0d-944e-4d55-a81d-e3eee9c9f260.png)
Step2:
![issue2 2](https://user-images.githubusercontent.com/99465982/225289599-ea24372a-2789-4fc5-ba96-c632f1402f5e.png)
AND THE MOMENT I HIT BACK BUTTON ON MY BROWSER IT DISPLAYS NOTHING!!
![issue2 3](https://user-images.githubusercontent.com/99465982/225289776-3f595d12-3477-44f8-89ef-b80f3af300e7.png)

## Environment
Not environment specific

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by sachinsh01** [comment]
Hello @nishchay-veer.  My name is Sachin Sharma, and I am interested to contribute to Creative Commons projects for GSOC 2023. I am interested in the "Modernize Resources Archive" project listed on the GSOC ideas page and this issue is a part of it. I would like to inquire about the availability of it and can I work on it?

**Comment by Cronus1007** [comment]
@nown1ne @sachinsh01  thanks for your interest to contribute on this project but it is not yet approved.
Please refer the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)  to understand the labels. Please find such issues which have been marked as `status: ready for work.`

**Comment by nown1ne** [comment]
Yeah sorry about that.
I have read the guidelines and also closed my PR.

**Comment by Xaid-vfx** [comment]
@possumbilities Yes, I would be happy to fix this.
