### ISSUE TITLE
[Feature] Expanding the abbreviations of languages

### ISSUE THREAD

**Issue by Javali-M** [creativecommons/cc-resource-archive#87]
## Problem
To increase user experience, I feel the languages should not just be stated in short forms as it may not strike the user or it might take a while to find the language he's looking for. [Happened with me initially]

## Description
So displaying the full name of the language would be great instead of the abbreviation. 

## Alternatives
An alternative would be to just have the languages all directly mentioned using filters.

## Implementation
- [x] I would be interested in implementing this feature.
Here is one way -
<img width="161" alt="image" src="https://user-images.githubusercontent.com/78152931/225885179-537c1d28-08df-479a-8d28-1681f416794a.png">

**Comment by possumbilities** [comment]
@Javali-M This a good point. I would go so far as to say that the links should likely spell out the language outright, and not need a hover tool-tip to achieve it. 

Thoughts?

**Comment by Javali-M** [comment]
@possumbilities yes, absolutely. I think that's the best solution if we aren't obliged to fit the languages into a certain section or box. I suggested the hover over tool aiming for a minimum space utilization as with the full forms it definitely would take up more area and we'd have to decrease the font size as well, resulting in the font sizes being uneven in comparison with the other sections.

**Comment by possumbilities** [comment]
@Javali-M I think it getting longer would be a problem worth having and solving in other ways like perhaps changing placement or layout in other Issues that might make it worth it to make the whole link more readable. 

I look forward to your PR here! ❤️

**Comment by possumbilities** [comment]
@Javali-M I like the bulleted list approach and I think that's a sound direction to go.

**Comment by Javali-M** [comment]
@possumbilities Right, thanks so much. I'll be working on this issue and report back at the earliest.

**Comment by Naman13Kumawat** [comment]
@Javali-M To make this feature more readable, why not write the languages in their corresponding language? For reference I've attached a picture. 
![image](https://user-images.githubusercontent.com/85545016/227631055-7207ffef-47d7-482c-a68d-e24b3eea17b0.png)
