### ISSUE TITLE
[Feature] Simplify navigation

### ISSUE THREAD

**Issue by subhamgcon** [creativecommons/cc-resource-archive#90]
## Problem
The Navigation of the resource page is not properly configured thus we should do a proper UX study and prepare a search button and list of sub-menus of users to navigate properly through the page
## Description

Using search box: Include a search box on your website to help users find the information they need quickly and easily. This is particularly useful for websites with extensive content or complex navigation.
Grouping similar items together: Group similar items together in a logical way that makes sense to your users. For example, if your website offers different types of products, group them together under a clear and concise label such as "Resource Type A" or "B".

Prioritize the most important and searched resource at the top: This helps users quickly find the information they need without having to navigate through multiple pages.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by Aditya9764** [comment]
Hii Ma'am
 Hope you are well
I am Aditya Kapse from last year Electronic and telecommunication at Government College of engineering , jalgaon with a consistent CGPA 8.5 .
I have knowledge of C,C++,HTML ,CSS,JS ,  programming language with framework Bootstrap,React and also have knowledge of Github  . 
I want of contribute in cc for the project "Modernize  CC resource "
I know I'm late but if you give me chance i will know everything about UI/UX Please look at my Web All webs are included in portfolio Github :-https://github.com/Aditya9764
 portfolio https://adityaportfolio97.netlify.app/
 gfg  :- 250+ Solved Problem in CPP - https://auth.geeksforgeeks.org/user/adityakapse0201/practice/codechef :- 100+ Solved Problem in CPPhttps://www.codechef.com/users/aditya9764
Please provide me slack invite link or direct workspace link I'm not able to join slack using slack info on our page

**Comment by possumbilities** [comment]
I'd suggest moving discussion to #23
