### ISSUE TITLE
[Feature] The Selected Filters are not displayed properly. Short forms are displayed.

### ISSUE THREAD

**Issue by Xaid-vfx** [creativecommons/cc-resource-archive#91]
## Problem
On selecting any specific Topic , Medium or Language. The selected niche is not displayed properly. Short forms are often displayed.

## Description
For example, On selecting  `Open Educational Resources ` , `oer` is displayed.
Check the following image:

<img width="173" alt="Screenshot 2023-03-19 at 5 48 04 AM" src="https://user-images.githubusercontent.com/77684943/226146942-9ea6c7e4-601d-4fcc-b9da-519ab432dfae.png">

This decreases User Experience and can be replaced by displaying actual Names of Filters.
Check the following image:

<img width="226" alt="Screenshot 2023-03-19 at 5 48 59 AM" src="https://user-images.githubusercontent.com/77684943/226147019-156c4335-dd2c-48a8-97a2-ce3d9ddf6ae7.png">

## Alternatives
A good alternative is that instead of removing the entire list of filters and displaying just the selected one, we can keep the entire list as it is and just highlight the selected filters using CSS.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Aditya9764** [comment]
Hey Sir ,
I'm new here but  i want to contribute in CC for GSOC can you please suggest me any communication channel or link to get familiar with codebase

**Comment by Parth-2609** [comment]
I would be interested in implementing this feature.

**Comment by Xaid-vfx** [comment]
Hey @Aditya9764 ,
This issue is not yet approved by the maintainers. You can still check other issues or raise a new one.

**Comment by BalrajDhakad** [comment]
I want to contribute to this issue, can you please guide me the very first step
