### ISSUE TITLE
[Feature] Remove expired form, encourage pull request.

### ISSUE THREAD

**Issue by itsyuxuan** [creativecommons/cc-resource-archive#93]
## Problem

The "[Submit a resource](https://resources.creativecommons.org/submit/)" page is broken as below. 
<img width="1392" alt="Screenshot 2023-03-20 at 10 33 15 pm" src="https://user-images.githubusercontent.com/62364938/226380968-fbcc40a1-67df-4d40-bdea-ffaa19d6e9ee.png">

The key problem is that the original Google Form has expired.
<img width="1392" alt="Screenshot 2023-03-20 at 10 32 57 pm" src="https://user-images.githubusercontent.com/62364938/226381284-9b5a276e-6b2a-4139-828e-25ae5e156733.png">

## Description

With the help of the [Wayback Machine](https://web.archive.org/), I get to know that the developer has long suggested not to use the form but to make pull requests instead. The original form isn't useful anymore.
<img width="1392" alt="Screenshot 2023-03-20 at 10 32 01 pm" src="https://user-images.githubusercontent.com/62364938/226381837-3213c3c4-87ff-4bbc-ad3d-eb6e56b2b94f.png">

Hence, I remove the link to the Google Form and encourage pull requests from anyone who needs to submit a resource. 
<img width="917" alt="Screenshot 2023-03-20 at 11 07 46 pm" src="https://user-images.githubusercontent.com/62364938/226382483-1efc52ec-53b3-47cd-bc24-8f0b3af87f86.png">

## Alternatives

The alternative solution for the Creative Commons members is to reopen an official form and replace the form link in the code. But as the community has a thorough system for contributing, filling forms is outdated and will increase the workload.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@itsyuxuan Thanks for this. I think this is a correct approach for now. Feel free to proceed!
