### ISSUE TITLE
Redesigning of Header and Including Navbar

### ISSUE THREAD

**Issue by shuence** [creativecommons/cc-resource-archive#94]
## Problem

To increase user experience, I feel the the topics medium and languages should be Navbar elements with a dropdown
As well as the logo and Name should be a header component

## Description

Here I used css to style the header and navbar and made few changes. when user hovers on the The topics or medium or languages section the dropdown menu will appear.

## Implementation

- [x] I would be interested in implementing this feature.
Before : 
![image](https://user-images.githubusercontent.com/65482186/226551636-92362ffd-663d-40ba-b1ba-b03c30cb1a03.png)
I Improved it and here is After View
After :

https://user-images.githubusercontent.com/65482186/226562250-18bc6d5d-51b5-4984-b4d8-c3ab99e47ef0.mp4

**Comment by possumbilities** [comment]
Hi and thanks for this contribution! But I believe this Issue covers items already mentioned in:

* #30 
* #90
* #23
* possibly #48

Closing as duplicated efforts. I'd suggest moving your conversation to one of the mentioned Issues here instead.
