### ISSUE TITLE
Restructure / Organize the Codebase

### ISSUE THREAD

**Issue by C-NikhilKarthik** [creativecommons/cc-resource-archive#95]
## Problem
The current codebase is not structured well.

## Description
The necessary files of this project are not well organized into folder structures. A proper organization of the same can be done on the basis of html pages, css files and other documentations such as the .md files etc.
This can help all contributors in easily understanding the codebase of this project.

## Current Structure
![Screenshot from 2023-03-21 23-15-44](https://user-images.githubusercontent.com/100520932/226696905-6cf68848-c14f-40e3-98a1-b2b3f58194a5.png)

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
@C-NikhilKarthik I agree on the idea of organizing things better, what route would you suggest keeping in mind it still has to function as a workable jekyll site?

**Comment by C-NikhilKarthik** [comment]
@possumbilities We could follow the git repository of jekyll, that is , arrange all the html files in a pages folder which can again contain the redirects folder. It also incorporates a css folder so as to distribute all the css into different files rather than writing all the css into one global file which because hard to maintain and update.

![Screenshot from 2023-03-22 02-29-44](https://user-images.githubusercontent.com/100520932/226739637-7da9effd-0b07-4cce-8bbe-9e74dd2ca8b9.png)
![Screenshot from 2023-03-22 02-30-08](https://user-images.githubusercontent.com/100520932/226739717-68bdc068-7433-47b9-82d4-5cc79236dfc0.png)

**Comment by C-NikhilKarthik** [comment]
@possumbilities is the above mentioned method sufficient for the codebase? Or should I consider a bit more for the restructuring of the same.

**Comment by C-NikhilKarthik** [comment]
@possumbilities  is the above mentioned method sufficient for the codebase? Or should I consider a bit more for the restructuring of the same. If you could provide the feedback then I can start working the same.

**Comment by justaskulkarni** [comment]
Issue #74 also deals with the restructuring of the codebase so the the discussion can take place as a part of a single issue than having multiple issues for the same.

**Comment by possumbilities** [comment]
I would say duplicate Issue, please move convo to #74
